//! Dynamic AGENTS.md document generator.

use std::sync::Arc;
use tokio::time::{sleep, Duration};
use tracing::{error, info};

use crate::engine::ports::{AgentRepository, TaskRepository};
use crate::orchestration::bus::{WorkspaceEvent, WorkspaceEventBus};
use crate::types::{Agent, Task, WorkspaceId};

/// Format agents and tasks into a managed Markdown document string.
pub fn format_agents_md(agents: &[Agent], tasks: &[Task]) -> String {
    let mut doc = String::new();
    doc.push_str("# Co-Force Workspace Orientation\n\n");
    doc.push_str(
        "> **Notice:** This document is automatically generated by the Co-Force orchestrator.\n\n",
    );

    doc.push_str("## 1. Active Workspace Agents\n\n");
    if agents.is_empty() {
        doc.push_str("No active agents registered in this workspace.\n\n");
    } else {
        doc.push_str("| Agent ID | Name | Role | State | Current Task |\n");
        doc.push_str("| :--- | :--- | :--- | :--- | :--- |\n");
        for agent in agents {
            let task_id_str = agent
                .current_task_id
                .as_ref()
                .map(|t| t.as_ref().to_string())
                .unwrap_or_else(|| "None".to_string());
            doc.push_str(&format!(
                "| `{}` | {} | {} | {:?} | `{}` |\n",
                agent.agent_id.as_ref(),
                agent.name,
                agent.role,
                agent.state,
                task_id_str
            ));
        }
        doc.push_str("\n");
    }

    doc.push_str("## 2. Task Backlog\n\n");
    if tasks.is_empty() {
        doc.push_str("No tasks recorded in this workspace.\n\n");
    } else {
        doc.push_str("| Task ID | Title | Status | Priority | Assignee |\n");
        doc.push_str("| :--- | :--- | :--- | :--- | :--- |\n");
        for task in tasks {
            let assignee_str = task
                .assigned_agent_id
                .as_ref()
                .map(|a| a.as_ref().to_string())
                .unwrap_or_else(|| "Unassigned".to_string());
            doc.push_str(&format!(
                "| `{}` | {} | {:?} | {} | `{}` |\n",
                task.task_id.as_ref(),
                task.title,
                task.status,
                task.priority,
                assignee_str
            ));
        }
        doc.push_str("\n");
    }

    doc
}

/// Dynamic document generator background worker loop.
pub async fn run_doc_generator(
    bus: WorkspaceEventBus,
    agent_repo: Arc<dyn AgentRepository>,
    task_repo: Arc<dyn TaskRepository>,
    workspace_id: WorkspaceId,
    output_path: Option<String>,
) {
    let mut rx = bus.subscribe();
    info!(
        "Starting dynamic doc generator daemon for workspace: {}",
        workspace_id.as_ref()
    );

    loop {
        // Wait for any workspace event
        let event = match rx.recv().await {
            Ok(e) => e,
            Err(_) => break,
        };

        // Filter events related to state changes that warrant a doc update
        let trigger = match event {
            WorkspaceEvent::AgentCheckedIn { .. } => true,
            WorkspaceEvent::FilesLocked { .. } => true,
            WorkspaceEvent::TaskUpdated { .. } => true,
            _ => false,
        };

        if !trigger {
            continue;
        }

        // Debounce: Sleep briefly to avoid rapid sequential writes
        sleep(Duration::from_secs(2)).await;

        // Query active state
        let agents = match agent_repo.list_active(&workspace_id).await {
            Ok(a) => a,
            Err(e) => {
                error!("DocGenerator failed to list active agents: {e}");
                continue;
            }
        };

        let tasks = match task_repo.list_by_workspace(&workspace_id, None).await {
            Ok(t) => t,
            Err(e) => {
                error!("DocGenerator failed to list workspace tasks: {e}");
                continue;
            }
        };

        let md_content = format_agents_md(&agents, &tasks);

        if let Some(ref path) = output_path {
            if let Err(e) = tokio::fs::write(path, &md_content).await {
                error!("DocGenerator failed to write AGENTS.md to {path}: {e}");
            } else {
                info!("DocGenerator successfully updated AGENTS.md at {path}");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{AgentId, AgentState, TaskId, TaskStatus};

    #[test]
    fn test_format_agents_md() {
        let agents = vec![Agent {
            agent_id: AgentId::from("a-1"),
            workspace_id: WorkspaceId::from("ws-1"),
            name: "Agent 1".to_string(),
            role: "Developer".to_string(),
            provider: None,
            machine_id: "m-1".to_string(),
            state: AgentState::Idle,
            current_task_id: Some(TaskId::from("t-1")),
            last_seen: None,
            created_at: None,
        }];

        let tasks = vec![Task {
            task_id: TaskId::from("t-1"),
            workspace_id: WorkspaceId::from("ws-1"),
            title: "Task 1".to_string(),
            objective: None,
            status: TaskStatus::InProgress,
            revision: 1,
            rework_cycle: 0,
            assigned_agent_id: Some(AgentId::from("a-1")),
            delegated_from_agent_id: None,
            parent_task_id: None,
            use_cases: None,
            prerequisites: None,
            verification_plan: None,
            required_skills: None,
            locked_files: None,
            impact_analysis: None,
            priority: 2,
            created_at: None,
            updated_at: None,
            completed_at: None,
        }];

        let md = format_agents_md(&agents, &tasks);
        assert!(md.contains("## 1. Active Workspace Agents"));
        assert!(md.contains("Agent 1"));
        assert!(md.contains("Task 1"));
    }
}
