//! OS Process Manager for spawning subagents (Lane 3 workers) and building spawn directives (Lane 2 clients).

use anyhow::{bail, Result};
use std::collections::HashMap;
use tokio::process::Command;

/// Directives generated by the server for Lane 2 clients to execute locally.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SpawnDirective {
    pub command: String,
    pub args: Vec<String>,
    pub env: HashMap<String, String>,
    pub cwd: String,
}

/// OS process manager to spawn worker pool agents on the server or build execution directives for clients.
pub struct ProcessManager;

impl ProcessManager {
    /// Builds a directive for client execution or local server spawning.
    pub fn build_directive(
        provider: &str,
        task_id: &str,
        token: &str,
        workspace_path: &str,
        is_l3: bool,
    ) -> Result<SpawnDirective> {
        let specs = crate::orchestration::providers::ProviderSpec::defaults();
        let spec = specs
            .iter()
            .find(|s| s.name == provider || s.binary_names.contains(&provider.to_string()))
            .ok_or_else(|| anyhow::anyhow!("Unsupported provider: {}", provider))?;

        if provider == "codex" && !is_l3 {
            bail!("SPAWN_DENIED: Codex requires L3 sandbox bypass flags for headless execution.");
        }

        let prompt = format!("Work on task {task_id}");
        let mut args = spec.render_headless_command(&prompt, workspace_path, task_id);

        if is_l3 {
            for flag in &spec.sandbox_bypass_flags {
                args.push(flag.clone());
            }
        } else {
            for flag in &spec.auto_approve_flags {
                args.push(flag.clone());
            }
        }

        let mut env = HashMap::new();
        env.insert("CO_FORCE_TOKEN".to_string(), token.to_string());

        Ok(SpawnDirective {
            command: spec.binary_names[0].clone(),
            args,
            env,
            cwd: workspace_path.to_string(),
        })
    }

    /// Spawns a subagent detached process locally on the server (Lane 3 worker).
    pub async fn spawn_local(directive: &SpawnDirective) -> Result<u32> {
        let mut cmd = Command::new(&directive.command);
        cmd.args(&directive.args);
        cmd.envs(&directive.env);

        // Only set current dir if it is not empty
        if !directive.cwd.is_empty() {
            cmd.current_dir(&directive.cwd);
        }

        let child = cmd.spawn()?;
        let pid = child.id().unwrap_or(0);

        // Spawn background task to monitor child process status and reap it upon termination
        tokio::spawn(async move {
            let mut child = child;
            let _ = child.wait().await;
        });

        Ok(pid)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_directive() {
        let dir = ProcessManager::build_directive("claude-code", "task-42", "tok-123", "/tmp", false).unwrap();
        assert_eq!(dir.command, "claude");
        assert_eq!(dir.env.get("CO_FORCE_TOKEN").unwrap(), "tok-123");
        assert_eq!(dir.cwd, "/tmp");
    }

    #[tokio::test]
    async fn test_spawn_local_invalid_command() {
        let dir = SpawnDirective {
            command: "nonexistent-cmd-xyz".to_string(),
            args: vec![],
            env: HashMap::new(),
            cwd: "".to_string(),
        };
        let result = ProcessManager::spawn_local(&dir).await;
        assert!(result.is_err());
    }
}
