//! OS Process Manager for spawning subagents (Lane 3 workers) and building spawn directives (Lane 2 clients).

use anyhow::{bail, Result};
use std::collections::HashMap;
use tokio::process::Command;

/// Directives generated by the server for Lane 2 clients to execute locally.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SpawnDirective {
    pub command: String,
    pub args: Vec<String>,
    pub env: HashMap<String, String>,
    pub cwd: String,
}

/// OS process manager to spawn worker pool agents on the server or build execution directives for clients.
pub struct ProcessManager;

impl ProcessManager {
    /// Builds a directive for client execution or local server spawning.
    pub fn build_directive(
        provider: &str,
        task_id: &str,
        token: &str,
        workspace_path: &str,
    ) -> Result<SpawnDirective> {
        let (command, args, env) = match provider {
            "claude-code" | "claude" => (
                "claude".to_string(),
                vec!["-p".to_string(), format!("Work on task {task_id}")],
                {
                    let mut map = HashMap::new();
                    map.insert("CO_FORCE_TOKEN".to_string(), token.to_string());
                    map
                },
            ),
            "antigravity" | "agy" => (
                "agy".to_string(),
                vec![
                    "--task".to_string(),
                    task_id.to_string(),
                    "--dangerously-skip-permissions".to_string(),
                ],
                {
                    let mut map = HashMap::new();
                    map.insert("CO_FORCE_TOKEN".to_string(), token.to_string());
                    map
                },
            ),
            "codex" => (
                "codex".to_string(),
                vec![
                    "exec".to_string(),
                    "--json".to_string(),
                    "--task".to_string(),
                    task_id.to_string(),
                ],
                {
                    let mut map = HashMap::new();
                    map.insert("CO_FORCE_TOKEN".to_string(), token.to_string());
                    map
                },
            ),
            other => bail!("Unsupported provider: {}", other),
        };

        Ok(SpawnDirective {
            command,
            args,
            env,
            cwd: workspace_path.to_string(),
        })
    }

    /// Spawns a subagent detached process locally on the server (Lane 3 worker).
    pub async fn spawn_local(directive: &SpawnDirective) -> Result<u32> {
        let mut cmd = Command::new(&directive.command);
        cmd.args(&directive.args);
        cmd.envs(&directive.env);

        // Only set current dir if it is not empty
        if !directive.cwd.is_empty() {
            cmd.current_dir(&directive.cwd);
        }

        let child = cmd.spawn()?;
        let pid = child.id().unwrap_or(0);

        // Spawn background task to monitor child process status and reap it upon termination
        tokio::spawn(async move {
            let mut child = child;
            let _ = child.wait().await;
        });

        Ok(pid)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_directive() {
        let dir = ProcessManager::build_directive("claude", "task-42", "tok-123", "/tmp").unwrap();
        assert_eq!(dir.command, "claude");
        assert_eq!(dir.env.get("CO_FORCE_TOKEN").unwrap(), "tok-123");
        assert_eq!(dir.cwd, "/tmp");
    }

    #[tokio::test]
    async fn test_spawn_local_invalid_command() {
        let dir = SpawnDirective {
            command: "nonexistent-cmd-xyz".to_string(),
            args: vec![],
            env: HashMap::new(),
            cwd: "".to_string(),
        };
        let result = ProcessManager::spawn_local(&dir).await;
        assert!(result.is_err());
    }
}
